# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ml.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x08ml.proto\x12\x08selector\"e\n\x0cSelectorPing\x12\x0c\n\x04user\x18\x01 \x01(\t\x12-\n\x06source\x18\x02 \x01(\x0e\x32\x1d.selector.SelectorPing.Source\"\x18\n\x06Source\x12\x06\n\x02VK\x10\x00\x12\x06\n\x02TG\x10\x01\"\x07\n\x05\x45mpty2e\n\x02ML\x12\x32\n\x07PingOne\x12\x16.selector.SelectorPing\x1a\x0f.selector.Empty\x12+\n\x07PingAll\x12\x0f.selector.Empty\x1a\x0f.selector.Emptyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ml_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_SELECTORPING']._serialized_start=22
  _globals['_SELECTORPING']._serialized_end=123
  _globals['_SELECTORPING_SOURCE']._serialized_start=99
  _globals['_SELECTORPING_SOURCE']._serialized_end=123
  _globals['_EMPTY']._serialized_start=125
  _globals['_EMPTY']._serialized_end=132
  _globals['_ML']._serialized_start=134
  _globals['_ML']._serialized_end=235
# @@protoc_insertion_point(module_scope)
