version: '3'

services:
  database:
    image: postgres:13.3
    volumes:
    - ../postgresql:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: "${POSTGRES_DATABASE}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
    ports:
     - 5432:5432
  grpc-server:
    build: .
    command: sh -c 'python3 main.py'
  grpc-client:
    build: client/
    command: sh -c 'python3 client.py'

