# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import ml_pb2 as ml__pb2


class SelectorStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SelectOne = channel.unary_unary(
                '/selector.Selector/SelectOne',
                request_serializer=ml__pb2.User.SerializeToString,
                response_deserializer=ml__pb2.Empty.FromString,
                )
        self.SelectAll = channel.unary_unary(
                '/selector.Selector/SelectAll',
                request_serializer=ml__pb2.Empty.SerializeToString,
                response_deserializer=ml__pb2.Empty.FromString,
                )


class SelectorServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SelectOne(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SelectAll(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SelectorServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SelectOne': grpc.unary_unary_rpc_method_handler(
                    servicer.SelectOne,
                    request_deserializer=ml__pb2.User.FromString,
                    response_serializer=ml__pb2.Empty.SerializeToString,
            ),
            'SelectAll': grpc.unary_unary_rpc_method_handler(
                    servicer.SelectAll,
                    request_deserializer=ml__pb2.Empty.FromString,
                    response_serializer=ml__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'selector.Selector', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Selector(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SelectOne(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/selector.Selector/SelectOne',
            ml__pb2.User.SerializeToString,
            ml__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SelectAll(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/selector.Selector/SelectAll',
            ml__pb2.Empty.SerializeToString,
            ml__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
