version: "3.9"


services:

  database:
    image: postgres:13.3
    volumes:
    - ./postgresql:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: "${POSTGRES_DB}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
    ports:
      - "5432:5432"


  client_service:
    build: client/
    depends_on:
      - database
    ports:
     - 80:80
     - 5000:5000
    command: sh -c 'python3 main.py'

  
  mlservice:
    build: ML
    
    depends_on:
      - database
    command: sh -c 'python3 main.py'

  telegram_selector:
    build: selector_services/telegram_selector/selector
    
    depends_on:
      - database


  vk_selector:
    build: selector_services/vk_selector
    
    depends_on:
      - database

  scheduler:
    build: scheduler

    depends_on: 
      - database

    command: sh -c 'python3 scheduler.py'

  