version: "3.9"


services:

  database:
    image: postgres:13.3
    volumes:
    - ./postgresql:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: "${POSTGRES_DB}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
    ports:
      - "5432:5432"


  client_service:
    build: client/
    depends_on:
      - postgres
    ports:
     - 80:80
  
  ml_service:
    build: ML
    
    depends_on:
      - postgres
    command: sh -c 'python3 main.py'

  telegram_selector:
    build: selector_services/telegram_selector
    
    depends_on:
      - postgres

  vk_selector:
    build: selector_services/vk_selector
    
    depends_on:
      - postgres

    

  