# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: selector.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0eselector.proto\x12\x08selector\"\x14\n\x04User\x12\x0c\n\x04user\x18\x01 \x01(\t\"\x07\n\x05\x45mpty2g\n\x08Selector\x12,\n\tSelectOne\x12\x0e.selector.User\x1a\x0f.selector.Empty\x12-\n\tSelectAll\x12\x0f.selector.Empty\x1a\x0f.selector.Emptyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'selector_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_USER']._serialized_start=28
  _globals['_USER']._serialized_end=48
  _globals['_EMPTY']._serialized_start=50
  _globals['_EMPTY']._serialized_end=57
  _globals['_SELECTOR']._serialized_start=59
  _globals['_SELECTOR']._serialized_end=162
# @@protoc_insertion_point(module_scope)
