# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import ml_pb2 as ml__pb2
import selector_pb2 as selector__pb2


class MLStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.PingOne = channel.unary_unary(
                '/selector.ML/PingOne',
                request_serializer=ml__pb2.SelectorPing.SerializeToString,
                response_deserializer=selector__pb2.Empty.FromString,
                )
        self.PingAll = channel.unary_unary(
                '/selector.ML/PingAll',
                request_serializer=selector__pb2.Empty.SerializeToString,
                response_deserializer=selector__pb2.Empty.FromString,
                )


class MLServicer(object):
    """Missing associated documentation comment in .proto file."""

    def PingOne(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PingAll(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MLServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'PingOne': grpc.unary_unary_rpc_method_handler(
                    servicer.PingOne,
                    request_deserializer=ml__pb2.SelectorPing.FromString,
                    response_serializer=selector__pb2.Empty.SerializeToString,
            ),
            'PingAll': grpc.unary_unary_rpc_method_handler(
                    servicer.PingAll,
                    request_deserializer=selector__pb2.Empty.FromString,
                    response_serializer=selector__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'selector.ML', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ML(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def PingOne(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/selector.ML/PingOne',
            ml__pb2.SelectorPing.SerializeToString,
            selector__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def PingAll(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/selector.ML/PingAll',
            selector__pb2.Empty.SerializeToString,
            selector__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
